export const typesRegister = {
  REGISTER: "REGISTER",
};

export const typesLogin = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
};

export const typesMonitors = {
  LIST_MONITORS: "LIST OF MONITORS",
  ADD_MONITOR: "ADD MONITOR",
  DELETE_MONITOR: "DELETE MONITOR",
  UPDATE_MONITOR: "UPDATE MONITOR",
  SEARCH_MONITORS: "SEARCH MONITORS",
};

export const typesMonitoring = {
  LIST_MONITORING: "LIST OF MONITORING",
  ADD_MONITORING: "ADD MONITORING",
  DELETE_MONITORING: "DELETE MONITORING",
  UPDATE_MONITORING: "UPDATE MONITORING",
  SEARCH_MONITORING: "SEARCH MONITORING",
};
